- name: Initialize a variable for volumes for guest "{{ item }}"
  vars:
  set_fact:
    volumes: []
  tags:
    - upgrade-guests

- name: Collect BIG-IP facts to determine the active and available software-volumes for guest "{{ item }}"
  bigip_device_facts:
    gather_subset:
      - software-volumes
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  register: ltm
  delegate_to: localhost
  tags:
    - upgrade-guests

- name: Find volume to install not active for guest "{{ item }}"
  set_fact:
    volumes: "{{ volumes|default([])+ [ item.name ] }}"
  when: 'item.active == "no"' 
  loop: "{{ ltm.software_volumes }}"
  tags:
    - upgrade-guests

