- name: Set random high volume when single slot
  set_fact:
    volume: "HD1.23"
  when: volumes | length == 0 
  tags:
    - upgrade-guests



- name: Install software on the VCMP guest "{{ item }}"
  f5networks.f5_modules.bigip_software_install:
    block_device_image: "{{ ISO_IMAGE }}"
    type: vcmp
    volume: "{{ volume }}"
    state: installed
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      server_port: 443
      timeout: 7200
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade-guests


