- name: Install software on the VCMP guest "{{ item }}"
  f5networks.f5_modules.bigip_software_install:
    block_device_image: "{{ ISO_IMAGE }}"
    type: vcmp
    volume: "{{ volume }}"
    state: installed
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade-guests

- name: Switchboot to "{{ volume }}" and Reboot - "{{ item }}"
  uri:
    url: "https://{{ item }}/mgmt/tm/sys"
    user: "{{ username }}"
    password: "{{ password }}"
    method: POST
    body: "{'command':'reboot','volume': '{{ volume }}' }"
    body_format: json
    validate_certs: no
  tags:
    - upgrade-guests

- name: Wait for "{{ item }}" to come back after reboot
  bigip_wait:
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      timeout: 3600
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade-guests