- name: Wait for "{{ item }}" to come back after reboot
  f5networks.f5_modules.bigip_wait:
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      timeout: 3600
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade-guests